name: Auto Patch Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Check for changes in src/
        id: changes
        run: |
          git fetch origin main
          # Skip if this is a version bump commit
          if [[ "${{ github.event.head_commit.message }}" == "ci: bump patch version" ]]; then
            echo "Skipping version bump commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          elif git diff --quiet HEAD~1 HEAD -- src; then
            echo "No changes detected in src/"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in src/"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Bump patch version
        if: steps.changes.outputs.changed == 'true'
        run: |
          npm version patch --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "ci: bump patch version"
          git tag v$(node -p "require('./package.json').version")
          git push --follow-tags
